name: CI

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - tonistiigi/binfmt:latest
        platforms:
          - linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        id: qemu
        with:
          platforms: ${{ matrix.platforms }}

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: ${{ steps.qemu.outputs.platforms }}
          tags: ghcr.io/${{ env.IMAGE_NAME }}:develop
